### ISSUE TITLE
PHP Unit Test Runs has no Test Cases

### ISSUE THREAD

**Issue by digracesion** [qase-tms/qase-phpunit#39]
**Description:**
When running PHP Unit tests, the test run that gets generated in QASE shows no test cases

**Expected Result:**
Running automated tests will generate an automated test run with test cases in QASE

**Actual Result:**
Running automated tests generates an automated test run with no test cases in QASE

**Steps to Reproduce**
1. Install QASE reporter `docker compose exec <container> composer require qase/phpunit-reporter`
2. Update the phpunit.xml file to include the QASE reporter (test suites information was redacted)
![image](https://github.com/qase-tms/qase-phpunit/assets/18523823/f8ecc0c8-9828-44b8-8429-9e5a90df22af)
3. From the Project Settings Page, enable auto test case creation 
![image](https://github.com/qase-tms/qase-phpunit/assets/18523823/7be0c90e-6330-450c-a7e4-ff60b8b1b675)
4. Run the tests `docker compose exec <container> php vendor/bin/phpunit`. Notice that although the test run is generated, the test cases are appearing as empty. --> [PROBLEM]
![image](https://github.com/qase-tms/qase-phpunit/assets/18523823/4f05311f-7720-4525-8d54-38abab11077c)

**Additional Notes:**
Test cases can't be run locally due to dependency issues, so the setup is being run on docker

**Comment by sklmx** [comment]
Hi @digracesion! Please check the output of the PHPUnit execution. Does it contain any errors?

**Comment by digracesion** [comment]
There were definitely entries showing that QASE is uploading the test run, but this is the end result of the test run:
![image](https://github.com/qase-tms/qase-phpunit/assets/18523823/871f48c0-1696-4ee7-8d2a-f412b6e29a67)
